#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
picom -f &
xrdb .xresources
$HOME/.config/polybar/launch.sh
bspc monitor -d I II III IV V
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color '#282828'
bspc config active_border_color '#282828'
bspc config focused_border_color '#928374'
bspc rule -a discord desktop='^3'
